# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2f6b8ff26bc8a324a55f960e776171424f16ff7f78472d285601ec40bfd757029cc3fe7accaeee2eea194394f69a5b269c5ebda9255847997718cd7ff0823f0

test:
  secret_key_base: f77d770614fbbb843cdc2f65c673aaa445993763963e8d2a2b4ad2ac9f8f280c7aa200ae59eb1bca58ff78dc192d44834f65a67c744560d44526ad3de6b04f3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
